[project]
name = "bitcoin-mcp"
version = "0.1.0"
description = "bitcoin mcp"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=3.0.0b1",
    "httpx",
    "mcp[cli]>=1.25.0",
]
