[project]
name = "bitcoin-mcp"
version = "0.1.0"
description = "bitcoin mcp"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp",
    "httpx",
    "mcp[cli]>=1.25.0",
    "typing",
]
